INVALID_DATASET = "INVALID_DATASET"
MISSING_REQUIRED_FEATURES = "MISSING_REQUIRED_FEATURES"
UNKNOWN_PROFILE_FIELDS = "UNKNOWN_PROFILE_FIELDS"
INVALID_FIELD_TYPE = "INVALID_FIELD_TYPE"
BUNDLE_LOAD_FAILED = "BUNDLE_LOAD_FAILED"
POLICY_NOT_FOUND = "POLICY_NOT_FOUND"
NO_RECOURSE_NEEDED = "NO_RECOURSE_NEEDED"
NO_FEASIBLE_CF_FOUND = "NO_FEASIBLE_CF_FOUND"
UFCE_EXECUTION_ERROR = "UFCE_EXECUTION_ERROR"
NO_VALID_FLIP = "NO_VALID_FLIP"
CONSTRAINT_BLOCKED = "CONSTRAINT_BLOCKED"
POLICY_OVERRIDE_INVALID = "POLICY_OVERRIDE_INVALID"
NO_CANDIDATE_GENERATED = "NO_CANDIDATE_GENERATED"
GENERATION_ERROR = "GENERATION_ERROR"
INVALID_COUNTERFACTUAL_BLOCKED = "INVALID_COUNTERFACTUAL_BLOCKED"
REQUEST_CONSTRAINTS_BLOCKED = "REQUEST_CONSTRAINTS_BLOCKED"
NO_FLIP = "NO_FLIP"
PROTECTED_FIELD_CHANGED = "PROTECTED_FIELD_CHANGED"
IMMUTABLE_FIELD_CHANGED = "IMMUTABLE_FIELD_CHANGED"
HARD_CONSTRAINT_VIOLATION = "HARD_CONSTRAINT_VIOLATION"
OUT_OF_DOMAIN_RANGE = "OUT_OF_DOMAIN_RANGE"
NON_ACTIONABLE_DELTA = "NON_ACTIONABLE_DELTA"
INCONSISTENT_DELTA_SUMMARY = "INCONSISTENT_DELTA_SUMMARY"
DUPLICATE_DOMINATED = "DUPLICATE_DOMINATED"

ALL_REASON_CODES = (
    INVALID_DATASET,
    MISSING_REQUIRED_FEATURES,
    UNKNOWN_PROFILE_FIELDS,
    INVALID_FIELD_TYPE,
    BUNDLE_LOAD_FAILED,
    POLICY_NOT_FOUND,
    NO_RECOURSE_NEEDED,
    NO_FEASIBLE_CF_FOUND,
    UFCE_EXECUTION_ERROR,
    NO_VALID_FLIP,
    CONSTRAINT_BLOCKED,
    POLICY_OVERRIDE_INVALID,
    NO_CANDIDATE_GENERATED,
    GENERATION_ERROR,
    INVALID_COUNTERFACTUAL_BLOCKED,
    REQUEST_CONSTRAINTS_BLOCKED,
    NO_FLIP,
    PROTECTED_FIELD_CHANGED,
    IMMUTABLE_FIELD_CHANGED,
    HARD_CONSTRAINT_VIOLATION,
    OUT_OF_DOMAIN_RANGE,
    NON_ACTIONABLE_DELTA,
    INCONSISTENT_DELTA_SUMMARY,
    DUPLICATE_DOMINATED,
)
