"""Reusable LR model bundle helpers for offline export and deterministic load."""

from ufce.model_bundles.lr_bundle import (
    BUNDLE_SCHEMA_VERSION,
    DEFAULT_ARTIFACT_VERSION,
    DEFAULT_DATASETS,
    DEFAULT_MAX_ITER,
    DEFAULT_MOVIE_SCALER_LOGIC_VERSION,
    DEFAULT_NON_MOVIE_SCALER_LOGIC_VERSION,
    DEFAULT_TEST_SIZE,
    DEFAULT_TRAINING_LOGIC_VERSION,
    DEFAULT_N_TRIES,
    DatasetModelBundle,
    build_movie_scalers,
    bundle_to_legacy_tuple,
    load_all_dataset_model_bundles,
    load_dataset_model_bundle,
    prepare_dataset_for_training,
    save_dataset_model_bundle,
    select_best_split,
    train_dataset_model_bundle,
    validate_bundle_against_metadata,
)

__all__ = [
    "BUNDLE_SCHEMA_VERSION",
    "DEFAULT_ARTIFACT_VERSION",
    "DEFAULT_DATASETS",
    "DEFAULT_MAX_ITER",
    "DEFAULT_MOVIE_SCALER_LOGIC_VERSION",
    "DEFAULT_NON_MOVIE_SCALER_LOGIC_VERSION",
    "DEFAULT_N_TRIES",
    "DEFAULT_TEST_SIZE",
    "DEFAULT_TRAINING_LOGIC_VERSION",
    "DatasetModelBundle",
    "build_movie_scalers",
    "bundle_to_legacy_tuple",
    "load_all_dataset_model_bundles",
    "load_dataset_model_bundle",
    "prepare_dataset_for_training",
    "save_dataset_model_bundle",
    "select_best_split",
    "train_dataset_model_bundle",
    "validate_bundle_against_metadata",
]
